name: Issue Comment Created

on:
  issue_comment:
    types: [created]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            waiting-reply
